spring.application.name=api

# Configurações do PostgreSQL (Conforme compose.yaml)
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

# Configurações do RabbitMQ (Conforme compose.yaml)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret